disabled_rules:
    - closure_parameter_position
    - todo
    - unused_optional_binding
    - type_name
    - identifier_name
opt_in_rules:
    - closure_body_length
    - closure_spacing
    - closure_end_indentation
    - collection_alignment
    - convenience_type
    - discouraged_optional_boolean
    - empty_count
    - empty_string
    - fallthrough
    - fatal_error_message
    - first_where
    - force_unwrapping
    - identical_operands
    - implicit_return
    - implicitly_unwrapped_optional
    - joined_default_parameter
    - last_where
    - literal_expression_end_indentation
    - lower_acl_than_parent
    - multiline_arguments
    - multiline_literal_brackets
    - multiline_parameters
    - nslocalizedstring_key
    - number_separator
    - weak_delegate
    - nimble_operator
    - object_literal
    - operator_usage_whitespace
    - overridden_super_call
    - override_in_extension
    - private_action
    - private_outlet
    - redundant_nil_coalescing
    - redundant_type_annotation
    - sorted_first_last
    - sorted_imports
    - toggle_bool
    - trailing_closure
    - unavailable_function
    - unneeded_parentheses_in_closure_argument
    - unused_import
    - unused_private_declaration
    - vertical_parameter_alignment_on_call
    - yoda_condition

force_unwrapping: error
force_try: warning

colon:
  flexible_right_spacing: false
  apply_to_dictionaries: true

closure_body_length:
  warning: 300
  error: 400

function_body_length:
  error: 200

type_body_length:
  warning: 300
  error: 400

cyclomatic_complexity:
  warning: 100
  error: 200
  ignores_case_statements: false

file_length:
  warning: 400
  error: 1000

number_separator:
  minimum_length: 0

implicitly_unwrapped_optional:
  mode: all_except_iboutlets

function_parameter_count:
  warning: 8
  error: 10

line_length:
  warning: 121
  error: 200
  ignores_urls: true
  ignores_function_declarations: false
  ignores_comments: false

large_tuple:
  warning: 8
  error: 10

excluded:
    - Carthage
    - Pods
    - .build
reporter: "xcode"
